config/routes.rb
Rails.application.routes.draw do
  resources :books
  get "login", to: 'sessions#new'
  post "login", to: 'sessions#create'
  get "welcome", to: "sessions#welcome"
  post "logout", to: "sessions#destroy"

  get "signup", to: 'users#new'
  post "users", to: "users#create"
  get "authorized", to: "sessions#page_requries_login"


  root "sessions#welcome"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  enum role: {patron: 0, librarian: 1}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to welcome_path unless logged_in?
  end
end

app/controllers/books_controller.rb
require 'pry'

class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    if params[:title].present?
      @books = Book.where("title LIKE ?", "#{params[:title]}%")
    else
      @books = Book.all
    end

    if turbo_frame_request?
      render partial: "books", locals: { books: @books }
    else
      render :index
    end
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to welcome_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil if logged_in?
    redirect_to welcome_path
  end

  def login
  end

  def welcome
  end

  def page_requries_login
  end

  private

  def login_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
require 'pry'

class UsersController < ApplicationController
  skip_before_action :authorized, only:[:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to welcome_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :role, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.haml
%tr{:id => "#{dom_id book}"}
  %td.pr-4
    = book.title

  %td
    = book.author

    -# = link_to "#{book.title} - #{book.author}", book_path(book), data: {turbo: false}

app/views/books/_books.html.haml
= turbo_frame_tag "books" do
  %table.table-auto
    %thead
      %tr
        %th.text-left Title
        %th.text-left Author
    %tbody
      = render books

app/views/books/_form.html.haml
= form_with(model: book, class: "space-y-3") do |form|
  - if book.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(book.errors.count, "error")
        prohibited this book from being saved:
      %ul
        - book.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :title, style: "display: block"
    = form.text_field :title, required: true
  %div
    = form.label :author, style: "display: block"
    = form.text_field :author, required: true
  %div
    = form.submit "Create", class: "bg-green-400 hover:bg-green-500 text-white font-semibold py-1 px-3 rounded-full"

app/views/books/edit.html.haml
%h1 Editing book
= render "form", book: @book
%br/
%div
  = link_to "Show this book", @book
  |
  \#{link_to "Back to books", books_path}

app/views/books/index.html.haml
%p{:style => "color: green"}= notice
%h1.text-lg.py-8 Search for Books
%div.space-y-4
  %div.w-full.max-w-xs
    = form_with(url: books_path, method: :get, class: "bg-white shadow-lg rounded px-8 pt-6 pb-6 mb-4", data: { turbo_frame: "books" }) do |f|
      %div.mb-4.space-y-3
        %span.py-1.px-3.cursor-pointer.mr-16.bg-blue-400.text-white.rounded-full Title
        %span.py-1.px-3.cursor-pointer Author

        %div.space-y-3
          = f.label :title, "Search by Title", class: "block text-gray-500 text-sm font-bold mb-2"
          = f.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-grey-500 leading-tight focus:outline-none focus:shadow-outline"
          = f.submit "Submit", class: "bg-green-400 hover:bg-green-500 text-white font-semibold py-1 px-3 rounded-full"

  %div
    = render "books", books: @books
  %div
    = link_to "New book", new_book_path, class: "bg-blue-400 hover:bg-blue-500 text-white font-semibold py-2 px-4 rounded-full"

app/views/books/new.html.haml
%p.text-xl.font-semibold New book
= render "form", book: @book
%br/
%div
  = link_to "Back to Search", books_path,  class: "bg-blue-400 hover:bg-blue-500 text-white font-semibold py-1 px-3 rounded-full"

app/views/books/show.html.haml
%p{:style => "color: green"}= notice
%div.space-y-3
  %p.text-xl.font-semibold= "#{@book.title} - #{@book.author}"
  %div.space-y-3
    = link_to "Edit this book", edit_book_path(@book), class: "bg-blue-400 hover:bg-blue-500 text-white font-semibold py-1 px-3 rounded-full"
    \#{link_to "Back to books", books_path, class: "bg-blue-400 hover:bg-blue-500 text-white font-semibold py-1 px-3 rounded-full"}

    \#{button_to "Destroy this book", @book, method: :delete, class: "bg-red-400 hover:bg-red-500 text-white font-semibold py-1 px-3 rounded-full"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Stimulus
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %div.container.mx-auto.my-16.px-10
      = render "shared/nav"
      = yield

app/views/shared/_nav.html.haml
%nav.flex.items-center.justify-between.flex-wrap.bg-blue-400.p-6
  %div.flex.items-center.flex-shrink-0.text-white.mr-6
    = link_to "Public Library", welcome_path, class: "span font-semibold text-xl tracking-tight"
  %div.w-full.block.flex-grow.lg-flex.lg:items-center.lg:w-auto
    %div.text-sm.lg:flex-grow
      - if logged_in?
        = button_to "Logout", logout_path, method: :post, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-200 hover:text-white mr-4"
      - else
        = link_to "Login", login_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-200 hover:text-white mr-4"
        = link_to "Sign Up", signup_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-200 hover:text-white mr-4"

app/views/users/_form.html.haml
= form_with(model: user, method: :post, class:"space-y-3") do |form|
  %div
    = form.label :name, style: "display: block"
    = form.text_field :name, required: true
  %div
    = form.label :email, style: "display: block"
    = form.text_field :email, requried: true
  %div
    = form.label :role, style: "display: block"
    = form.select(:role, [["Patron", "patron"],["Librarian", "librarian", disabled: true]], include_blank: "Select", requried: true)
  %div
    = form.label :password, style: "display: block"
    = form.password_field :password, required: true
  %div
    = form.label :password_confirmation, style: "display: block"
    = form.password_field :password_confirmation, required: true
  %div
    = form.submit class: "bg-green-400 hover:bg-green-500 text-white font-semibold py-1 px-3 rounded-full"

app/views/users/new.html.haml
%span.text-xl.font-semibold.pb-3 Sign Up
= render "form", user: @user